"""create core tables

Revision ID: 111124541f10
Revises: 
Create Date: 2026-09-04 01:32:14.859824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '111124541f10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('source_site', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_job_postings_user_url')
    )
    op.create_index(op.f('ix_job_postings_user_id'), 'job_postings', ['user_id'], unique=False)
    op.create_table('portfolio_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_projects_user_id'), 'portfolio_projects', ['user_id'], unique=False)
    op.create_table('resume_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('self_repoted_tech', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_profiles_user_id'), 'resume_profiles', ['user_id'], unique=False)
    op.create_table('fit_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('matched_skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('missing_skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('grade', sa.Enum('STRONG_RECOMMEND', 'RECOMMEND', 'REVIEW', 'NOT_RECOMMEND', name='fit_grade'), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_scores_job_id'), 'fit_scores', ['job_id'], unique=False)
    op.create_index(op.f('ix_fit_scores_user_id'), 'fit_scores', ['user_id'], unique=False)
    op.create_table('github_repo_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_project_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('readme_summary', sa.Text(), nullable=True),
    sa.Column('verified_tech', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_project_id'], ['portfolio_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_project_id')
    )
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('INTERESTED', 'EXCLUDED', name='feedback_action'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedbacks_job_id'), 'user_feedbacks', ['job_id'], unique=False)
    op.create_index(op.f('ix_user_feedbacks_user_id'), 'user_feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedbacks_user_id'), table_name='user_feedbacks')
    op.drop_index(op.f('ix_user_feedbacks_job_id'), table_name='user_feedbacks')
    op.drop_table('user_feedbacks')
    op.drop_table('github_repo_analyses')
    op.drop_index(op.f('ix_fit_scores_user_id'), table_name='fit_scores')
    op.drop_index(op.f('ix_fit_scores_job_id'), table_name='fit_scores')
    op.drop_table('fit_scores')
    op.drop_index(op.f('ix_resume_profiles_user_id'), table_name='resume_profiles')
    op.drop_table('resume_profiles')
    op.drop_index(op.f('ix_portfolio_projects_user_id'), table_name='portfolio_projects')
    op.drop_table('portfolio_projects')
    op.drop_index(op.f('ix_job_postings_user_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
