"""add verified/unverified matched skills to fit_scores

Revision ID: 26cbbcc0576d
Revises: 739aed9094e1
Create Date: 2026-09-07 15:25:11.357606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26cbbcc0576d'
down_revision: Union[str, None] = '739aed9094e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fit_scores', sa.Column('verified_matched_skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('fit_scores', sa.Column('unverified_matched_skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fit_scores', 'unverified_matched_skills')
    op.drop_column('fit_scores', 'verified_matched_skills')
    # ### end Alembic commands ###
