"""fix self_reported_tech column name typo

Revision ID: 739aed9094e1
Revises: 111124541f10
Create Date: 2026-09-04 17:30:16.478274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '739aed9094e1'
down_revision: Union[str, None] = '111124541f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_profiles', sa.Column('self_reported_tech', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.drop_column('resume_profiles', 'self_repoted_tech')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_profiles', sa.Column('self_repoted_tech', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.drop_column('resume_profiles', 'self_reported_tech')
    # ### end Alembic commands ###
